export const words = {
    "blocks": "Building units",
    "crafting": "Making items",
    "mining": "Gathering resources",
    "building": "Creating structures",
    "survival": "Avoiding death",
    "creeper": "Explosive mob",
    "redstone": "For circuits",
    "diamond": "Rare gem",
    "pickaxe": "Mining tool",
    "sword": "Combat weapon",
    "enderman": "Teleporting mob",
    "nether": "Fiery dimension",
    "villager": "Trading NPCs",
    "farming": "Growing crops",
    "biomes": "Unique regions",
    "steve": "Default male skin",
    "alex": "Default female skin",
    "bedrock": "Unbreakable block",
    "zombie": "Undead mob",
    "skeleton": "Archer mob",
    "spider": "Wall-climbing mob",
    "ghast": "Fireball shooter",
    "elytra": "Gliding wings",
    "obsidian": "Water and lava",
    "portal": "Dimensional gateway",
    "torch": "Light source",
    "furnace": "Smelting block",
    "chest": "Storage block",
    "hopper": "Transfers items",
    "potion": "Consumable buffs",
    "brewery": "Makes potions",
    "enchanting": "Enhances gear",
    "anvil": "Repairs and renames",
    "armor": "Protective gear",
    "food": "Replenishes hunger",
    "mobs": "All creatures",
    "spawn": "Where things appear",
    "fishing": "Catch items",
    "rail": "Minecart tracks",
    "beacon": "Provides buffs",
    "map": "For navigation",
    "compass": "Points to spawn",
    "tnt": "Explosive block",
    "snowball": "Throwable item",
    "boat": "Water transport",
    "wool": "From sheep",
    "shears": "Harvests wool",
    "shield": "Blocks attacks",
    "pig": "Rideable mob",
    "axe": "Chopping tool",
    "torch": "Light source",
    "dirt": "Common block",
    "ore": "Resource block",
    "lava": "Hot liquid",
    "wood": "Building material",
    "stone": "Basic block",
    "armor": "Body protection",
    "fish": "Water food",
    "bow": "Ranged weapon",
    "seed": "For planting",
    "wolf": "Tameable mob",
    "cat": "Tameable pet",
    "sheep": "Wool provider",
    "cow": "Leather source",
    "horse": "Rideable mob",
    "saddle": "Riding item",
    "book": "Enchanting base",
    "gold": "Shiny metal",
    "iron": "Strong metal",
    "chicken": "Feather source",
    "apple": "Tree fruit",
    "melon": "Farm fruit",
    "cake": "Crafted dessert",
    "egg": "From chickens"
}
